-- MySQL Script generated by MySQL Workbench
-- Tue Jun 13 15:55:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `correo` VARCHAR(60) NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `apellidos` VARCHAR(40) NOT NULL,
  `contraseña` VARCHAR(30) NOT NULL,
  `peso_kg` DECIMAL(5,2) NOT NULL,
  `estatura_m` DECIMAL(3,2) NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  `icono` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`correo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INSTRUCTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSTRUCTOR` (
  `idInstructor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `apellidos` VARCHAR(40) NOT NULL,
  `peso_kg` DECIMAL(5,2) NOT NULL,
  `estatura_m` DECIMAL(3,2) NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`idInstructor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TARIFA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TARIFA` (
  `nombre` VARCHAR(15) NOT NULL,
  `duracion_horas` TINYINT(2) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAGO` (
  `idPAGO` INT NOT NULL AUTO_INCREMENT,
  `TARIFA_nombre` VARCHAR(15) NOT NULL,
  `USUARIO_correo` VARCHAR(60) NOT NULL,
  `fecha_pago` DATETIME NOT NULL,
  `monto` DOUBLE NOT NULL,
  PRIMARY KEY (`idPAGO`, `TARIFA_nombre`, `USUARIO_correo`),
  INDEX `fk_PAGO_USUARIO_idx` (`USUARIO_correo` ASC) VISIBLE,
  INDEX `fk_PAGO_TARIFA1_idx` (`TARIFA_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_PAGO_USUARIO`
    FOREIGN KEY (`USUARIO_correo`)
    REFERENCES `mydb`.`USUARIO` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAGO_TARIFA1`
    FOREIGN KEY (`TARIFA_nombre`)
    REFERENCES `mydb`.`TARIFA` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ASISTENCIA_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASISTENCIA_USUARIO` (
  `idAsistencia` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_correo` VARCHAR(60) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_entrada` TIME NOT NULL,
  `hora_salida` TIME NOT NULL,
  PRIMARY KEY (`idAsistencia`, `USUARIO_correo`),
  CONSTRAINT `fk_ASISTENCIA_USUARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_correo`)
    REFERENCES `mydb`.`USUARIO` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ASISTENCIA_INSTRUCTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASISTENCIA_INSTRUCTOR` (
  `idInstructor` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_entrada` TIME NOT NULL,
  `hora_salida` TIME NOT NULL,
  PRIMARY KEY (`idInstructor`),
  CONSTRAINT `fk_ASISTENCIA_INSTRUCTOR_INSTRUCTOR1`
    FOREIGN KEY (`idInstructor`)
    REFERENCES `mydb`.`INSTRUCTOR` (`idInstructor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLASE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLASE` (
  `idInstructor` INT NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  `duracion_horas` TINYINT(2) NOT NULL,
  PRIMARY KEY (`idInstructor`, `nombre`),
  CONSTRAINT `fk_CLASE_INSTRUCTOR1`
    FOREIGN KEY (`idInstructor`)
    REFERENCES `mydb`.`INSTRUCTOR` (`idInstructor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX idx_nombre ON CLASE (nombre);


-- -----------------------------------------------------
-- Table `mydb`.`CLASES_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLASES_CLIENTE` (
  `USUARIO_correo` VARCHAR(60) NOT NULL,
  `CLASE_nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`USUARIO_correo`, `CLASE_nombre`),
  INDEX `fk_CLASES_CLIENTE_CLASE1_idx` (`CLASE_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_CLASES_CLIENTE_USUARIO1`
    FOREIGN KEY (`USUARIO_correo`)
    REFERENCES `mydb`.`USUARIO` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLASES_CLIENTE_CLASE1`
    FOREIGN KEY (`CLASE_nombre`)
    REFERENCES `mydb`.`CLASE` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `mydb`.`instructor` (`idInstructor`, `nombre`, `apellidos`, `peso_kg`, `estatura_m`, `fecha_de_nacimiento`) VALUES ('1', 'Dylan', 'Ojeda', '96', '1.80', '2001-12-25');
